Add a Debug command

diff --git a/.github/workflows/terraform-lifecycle.yml b/.github/workflows/terraform-lifecycle.yml
--- a/.github/workflows/terraform-lifecycle.yml
+++ b/.github/workflows/terraform-lifecycle.yml
@@ -4,11 +4,11 @@ on:
   workflow_dispatch:
     inputs:
       stage:
-        description: 'Environment (Dev or Prod)'
+        description: "Environment (Dev or Prod)"
         required: true
         default: Dev
       action:
-        description: 'Terraform action (apply or destroy)'
+        description: "Terraform action (apply or destroy)"
         required: true
         default: apply
 
@@ -16,8 +16,8 @@ on:
     branches:
       - main
     tags:
-      - 'deploy-dev'
-      - 'deploy-prod'
+      - "deploy-dev"
+      - "deploy-prod"
 
 jobs:
   terraform:
@@ -93,23 +93,37 @@ jobs:
         run: terraform destroy -auto-approve -var-file="${STAGE_LOWER}_config.tfvars"
         working-directory: terraform
 
+      - name: Debug Terraform Outputs
+        if: env.ACTION == 'apply'
+        run: terraform output
+        working-directory: terraform
+
+
       - name: Get EC2 Public IP
-        id: writeonly_instance_public_ip
+        working-directory: terraform
+        id: ec2_ip
+        if: env.ACTION == 'apply'
         run: |
-            EC2_IP=$(terraform output -raw writeonly_instance_public_ip)
-            echo "EC2_IP=$EC2_IP" >> "$GITHUB_ENV"
-      
+          set -e
+          EC2_IP=$(terraform output -raw      writeonly_instance_public_ip 2>/dev/null || echo "")
+          if [[ -z "$EC2_IP" ]]; then
+            echo "Terraform output for      writeonly_instance_public_ip is empty or failed."
+            exit 1
+          fi
+          echo "EC2_IP=$EC2_IP" >> "$GITHUB_ENV"
 
       - name: Wait for port 80 to be available
+        working-directory: terraform
+        if: env.ACTION == 'apply'
         run: |
-            for i in {1..10}; do
-              echo "Checking if port 80 is reachable on $EC2_IP..."
-              if curl -s --head "http://$EC2_IP" | grep "200 OK" > /dev/null; then
-                echo "App is up and serving on port 80"
-                exit 0
-              fi
-              echo "App not ready yet. Retrying in 10 seconds..."
-              sleep 10
-            done
-            echo "Timeout: App not reachable on port 80"
-            exit 1
+          for i in {1..10}; do
+            echo "Checking if port 80 is reachable on $EC2_IP..."
+            if curl -s --head "http://$EC2_IP" | grep "200 OK" > /dev/null; then
+              echo "App is up and serving on port 80"
+              exit 0
+            fi
+            echo "App not ready yet. Retrying in 10 seconds..."
+            sleep 10
+          done
+          echo "Timeout: App not reachable on port 80"
+          exit 1
