use GITHUB_OUTPUT

diff --git a/.github/workflows/terraform-lifecycle.yml b/.github/workflows/terraform-lifecycle.yml
--- a/.github/workflows/terraform-lifecycle.yml
+++ b/.github/workflows/terraform-lifecycle.yml
@@ -104,13 +104,15 @@ jobs:
         id: ec2_ip
         if: env.ACTION == 'apply'
         run: |
-          set -e
-          EC2_IP=$(terraform output -raw      writeonly_instance_public_ip 2>/dev/null || echo "")
-          if [[ -z "$EC2_IP" ]]; then
-            echo "Terraform output for      writeonly_instance_public_ip is empty or failed."
-            exit 1
-          fi
-          echo "EC2_IP=$EC2_IP" >> "$GITHUB_ENV"
+              set -e
+              EC2_IP=$(terraform output -raw writeonly_instance_public_ip 2>/dev/null || echo "")
+              if [[ -z "$EC2_IP" ]]; then
+                echo "Terraform output for writeonly_instance_public_ip is empty or failed."
+                exit 1
+              fi
+              echo "ec2_ip=$EC2_IP" >> "$GITHUB_OUTPUT"
+
+
 
       - name: Wait for port 80 to be available
         working-directory: terraform
